name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: update all submodules
      run: git submodule update --init --recursive
    - name: install restclient
      run: |
        git clone https://github.com/mrtazz/restclient-cpp.git
        sudo sudo apt install libcurl4-openssl-dev -y
        cd restclient-cpp
        ./autogen.sh
        ./configure 
        sudo make install
        sudo cp /usr/local/lib/librestclient-cpp.so.1 /usr/lib
    - name: install json
      run: |
        git clone https://github.com/nlohmann/json.git 
        cd json/include
        sudo cp -r nlohmann /usr/local/include
    - name: install args
      run: |
        git clone https://github.com/Taywee/args.git
        cd args
        sudo make install
    - name: make
      run: |
        cd ./cpp/lopdns-api-client
        make
    - uses: actions/upload-artifact@v4
      with:
        name: lopdns-api-client
        path: cpp/lopdns-api-client/lopdns-api-client
